name: untethered word
favicon: null
layout_spectrum: 0.5551301736850291
typography_spectrum: 0.03547732485458255
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.797352405032143
  lightness: 0.19459715066477656
  saturation: 0.7732928153127432
  rhythmicContrast: 0.3805076782591641
purpose: []
